# Generated by Django 4.2.7 on 2023-12-03 20:32

from django.db import migrations
import entities.customer.managers


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects', entities.customer.managers.CustomerManager()),
            ],
        ),
    ]
